### ISSUE TITLE
Add Database 

### ISSUE THREAD

**Issue by Hashir-Umar** [Hashir-Umar/hostel.info#1]
Make database named "hostel"

Make a php file to connect this database. (database_connection.php)

Make following tables
                    1) users (id, username, email, password, created_at, updated_at)
                    2) hostels (id, name, rooms, extras, rating, images, address, hostel_owner(user_id as FK), created_at, updated_at )
                    3) universities (id, name, address, city, created_at, updated_at)
                    4) hostels_universities (id, hostel_id, university_id, created_at, updated_at)

Make a php file to initialize this database. (database_init.php)
Move those php files to server folder

**Comment by ranaumair97** [comment]
added an extra table named "hostels_images" to store multiple images for each hostel
