### ISSUE TITLE
Login Page Validation

### ISSUE THREAD

**Issue by Hashir-Umar** [Hashir-Umar/hostel.info#2]
validate a user on client + server side 
validate both email and password (should be in correct pattern and present in the table named "users")

Add your client side code to src -> js -> validation.js and server side code to server -> validateForm.php
After successful validation take user to home page.

Follow naming convention.

**Comment by Hashir-Umar** [comment]
read about onsubmit() function for client side validation
https://www.w3schools.com/jsref/event_onsubmit.asp

**Comment by ranaumair97** [comment]
add your validation code to server -> validateForm.php
