### ISSUE TITLE
Signup Form Validation

### ISSUE THREAD

**Issue by Hashir-Umar** [Hashir-Umar/hostel.info#3]
validate a user on client + server side
validate both email and password (should be in correct pattern and present in the table named "users")

Add your client side code to src -> js -> validation.js and server side code to server -> validateForm.php
After successful validation take user to home page.

read about onsubmit() function for client side validation
https://www.w3schools.com/jsref/event_onsubmit.asp

Follow naming convention.

**Comment by Hashir-Umar** [comment]
Remove unnecessary fields like date of birth.
Make an option for admin like you did in our android project

**Comment by ranaumair97** [comment]
Add your validation code to server -> validateForm.php
